pipeline {
    agent any

    tools {
        // Le nom doit correspondre à "Global Tool Configuration"
        maven 'mvn' 
    }

    environment {
        // Nom de l'image Docker
        DOCKER_IMAGE = "tp30-demo-app"
    }

    stages {
        stage('Checkout') {
            steps {
                // Récupère le code du repo configuré dans le Job
                checkout scm
            }
        }

        stage('Build & Test') {
            steps {
                echo 'Building and Testing...'
                // Utilisation de 'sh' car Jenkins est sous Linux (Docker)
                sh 'mvn clean package'
            }
        }

        stage('Docker Build') {
            steps {
                echo 'Building Docker Image...'
                sh "docker build -t ${DOCKER_IMAGE} ."
            }
        }

        stage('Docker Run') {
            steps {
                echo 'Running Docker Container...'
                script {
                    // Arrêter le conteneur s'il existe déjà pour éviter les conflits
                    try {
                         sh "docker stop ${DOCKER_IMAGE} || true"
                         sh "docker rm ${DOCKER_IMAGE} || true"
                    } catch (Exception e) {
                        echo "Pas de conteneur à supprimer"
                    }
                    
                    // Lancement du nouveau conteneur
                    sh "docker run -d -p 8081:8080 --name ${DOCKER_IMAGE} ${DOCKER_IMAGE}"
                }
            }
        }
    }
}
